### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by angeloh** [xcmyz/FastSpeech#1]
Hello Zhengxi,

Will you provide the pre-trained model?

- Angelo

**Comment by angeloh** [comment]
Is this implementation ready to use for training?

**Comment by xcmyz** [comment]
No, I won't provide the pre-trained model and this implementation is ready to use but you need write alignment.py by yourself.

**Comment by angeloh** [comment]
Do you have any tips for writing the alignment.py?

**Comment by xcmyz** [comment]
I will but you need to wait for some time.

**Comment by xcmyz** [comment]
Now you don't need to rewrite alignment.py. I use Tacotron2 published by NVIDIA to provide alignment and you can use it directly.

**Comment by xcmyz** [comment]
Now you don't need a pre-trained model to train FastSpeech. I have used Tacotron2 to calculate all the alignments of LJSpeech. I put these in alignment_targets.zip and you just need unzip it.

**Comment by alokprasad** [comment]
where i can find alignment_targets.zip ?
