### ISSUE TITLE
Result voice is bad compared to Tacotron2

### ISSUE THREAD

**Issue by angeloh** [xcmyz/FastSpeech#10]
Why is the WAV result in the results folder so bad? It is because fast speech just can't produce good results compared to Tacotron2. Will the result from the paper's author be better than your results?

**Comment by xcmyz** [comment]
I didn't use neural vocoder. And the model need to be trained for more epochs.

**Comment by angeloh** [comment]
So if we use Waveglow the result will be better?

**Comment by xcmyz** [comment]
Yes.

**Comment by dpny518** [comment]
but waveglow is the slow part, the synthesizer is fast part of the pipeline
