### ISSUE TITLE
Training slower with multiple GPU's

### ISSUE THREAD

**Issue by ghost** [xcmyz/FastSpeech#11]
Hi, the training time for each step was slower when using multiple GPU's.

I'm running:
`CUDA_VISIBLE_DEVICES=0,1,2,3 python3 train_accelerated.py`

And for single GPU:
`CUDA_VISIBLE_DEVICES=0 python3 train_accelerated.py`

I can fit batch_size=16 in a single gpu so I tried with batch_size=16 for single and multi-gpu.

I also tried batch_size=64 for the multi-gpu case.

**Comment by xcmyz** [comment]
It is common that training is slower with multiple GPUs.
