### ISSUE TITLE
about alignment.py

### ISSUE THREAD

**Issue by SerialLain3170** [xcmyz/FastSpeech#17]
Hi, Thank you for excellent source!

You mentioned `Run alignment.py, it will spend 7 hours training on NVIDIA RTX2080ti.` in README.md.
But, this command yields only one alignment from text("I want to go to CMU to do research on deep learning."). How do I fix alignment.py ?

**Comment by nipengmath** [comment]
`def process_text(train_text_path):

    hparams = hp_tacotron2.create_hparams()
    hparams.sampling_rate = hp.sample_rate

    checkpoint_path = os.path.join("Tacotron2", os.path.join(
        "pre_trained_model", "tacotron2_statedict.pt"))

    tacotron2 = train_tacotron2.load_model(hparams)
    state_dict = torch.load(checkpoint_path)['state_dict']

    tacotron2.load_state_dict(state_dict)
    _ = tacotron2.cuda().eval().half()

    with open(train_text_path, "r", encoding="utf-8") as f:
        inx = 0
        txt = []
        for line in f.readlines():
            cnt = 0
            l = line.strip().split("|")
            cid = l[0]
            n = int(cid.replace(".npy", "").split("-")[-1])
            text_seq = l[-1]
            sequence = np.array(text_to_sequence(text_seq, hp.text_cleaners))[None, :]
            sequence = torch.autograd.Variable(
                torch.from_numpy(sequence)).cuda().long()

            mel, mel_postnet, _, alignment = tacotron2.inference(sequence)
            alignment = alignment.float().data.cpu().numpy()[0]
            alignment = get_D(alignment)

            np.save("alignment_targets/%s.npy" %n, alignment)

        return txt`

this is my alignment, but i don't know if it is right @xcmyz

**Comment by SerialLain3170** [comment]
Thanks. I'll try it
