### ISSUE TITLE
Should we change sample_rate=20000 to 22050 in FastSpeech/hparams.py? Other related params may also need to change correspondingly, thank you.

### ISSUE THREAD

**Issue by hxs7709** [xcmyz/FastSpeech#2]
First of all, thanks for your quick and great implementation.
The default sample rate is 22050 for LJSpeech-1.1 wavs, Tacotron2/hparams.py, and possibly the used pre-trained Tacotron2 model published by NVIDIA. 
So, should we change sample_rate=20000 to 22050 in FastSpeech/hparams.py? Other related params may also need to change correspondingly.
Please check and help on this issue, thank you.

**Comment by xcmyz** [comment]
Oh, I'm sorry about that. Yeah, of course you can.

**Comment by hxs7709** [comment]
Great! 
A quick question: with your code in this deposit, can you get the similar results like pater with LJSpeech dataset? Also, have you tried with Chinese data set? Hope to get your synthesized wav shared here, thank you.

**Comment by xcmyz** [comment]
This model is still training on the sever. I haven't tried Chinese dataset.

**Comment by hxs7709** [comment]
Thank you!
