### ISSUE TITLE
我在选择由Tacotron2计算的LJSpeech的比对alignment_targets.zip

### ISSUE THREAD

**Issue by 756890911** [xcmyz/FastSpeech#23]
解压后，还需要如何对代码做相应更改

**Comment by 1105060120** [comment]
@756890911  你好，请问你是如何处理对齐的。

**Comment by 756890911** [comment]
我用的就是楼主给的训练好的版本------------------ 原始邮件 ------------------
发件人: "1105060120"<notifications@github.com>
发送时间: 2019年10月21日(星期一) 上午9:40
收件人: "xcmyz/FastSpeech"<FastSpeech@noreply.github.com>;
抄送: "756890911"<756890911@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xcmyz/FastSpeech] 我在选择由Tacotron2计算的LJSpeech的比对alignment_targets.zip (#23)



@756890911  你好，请问你是如何处理对齐的。
 
&mdash;

**Comment by 1105060120** [comment]
@756890911  你好，请问你是否出现如下问题，我在run alignment.py时，提升如下，谢谢

sequence size (1, 52)
alignment size (280, 52)
[[8.4814453e-01 4.4107437e-04 2.3097992e-03 ... 6.3121319e-05
  6.3180923e-04 6.0485840e-02]
 [5.0878906e-01 3.0456543e-02 5.9143066e-02 ... 1.8644333e-03
  2.0351410e-03 8.3740234e-02]
 [7.2167969e-01 5.1666260e-02 2.2659302e-02 ... 1.5249252e-03
  3.7670135e-03 3.7139893e-02]
 ...
 [1.5268326e-03 1.5497208e-06 5.7756901e-05 ... 6.8855286e-04
  3.6376953e-02 8.6767578e-01]
 [1.2187958e-03 8.3446503e-07 4.3809414e-05 ... 4.5943260e-04
  1.5319824e-02 8.7207031e-01]
 [1.6145706e-03 8.9406967e-07 5.3465366e-05 ... 2.7203560e-04
  8.9721680e-03 8.8183594e-01]]
