### ISSUE TITLE
forward() missing 2 required positional arguments: 'src_seq' and 'src_pos' when do synthesis.py 

### ISSUE THREAD

**Issue by li-xx-5** [xcmyz/FastSpeech#26]
My pytorch model is 1.0.1.Is that the reason that the pytorch is the wrong model.

**Comment by idgmatrix** [comment]
I have same issue with PyTorch 1.1.0 and CUDA 9.0

**Comment by 1105060120** [comment]
@idgmatrix  hello,how did you solve that?

**Comment by idgmatrix** [comment]
> @idgmatrix hello,how did you solve that?

Sorry, No, I didn't
