### ISSUE TITLE
Solved the slow training problem

### ISSUE THREAD

**Issue by tianrengao** [xcmyz/FastSpeech#27]
After analyzing, I found the reason of slow training speed. The code is not optimized for parallel data training. I optimized the distributed data-parallel loader. I will create a pull request later. 

BTW, the author os FastSpeech paper should publish their code soon. They say they will publish it once the paper is accepted. This repo is a very good resource, but it needs more maintains and optimization.

希望作者能够更多的参与github和知乎上的讨论，非常感谢

**Comment by trfnhle** [comment]
FastSpeech paper seem to be accepted at NIPS 2019, but the authors still do not publish code.

**Comment by ntzzc** [comment]
@tianrengao Terry, I googled about the distribute data loader and you are right, it will speed up data loading. would you mind share your code? I'm trying to train a model but it really slow. thanks

**Comment by xcmyz** [comment]
> After analyzing, I found the reason of slow training speed. The code is not optimized for parallel data training. I optimized the distributed data-parallel loader. I will create a pull request later.
> 
> BTW, the author os FastSpeech paper should publish their code soon. They say they will publish it once the paper is accepted. This repo is a very good resource, but it needs more maintains and optimization.
> 
> 希望作者能够更多的参与github和知乎上的讨论，非常感谢

使用新版本的代码，我优化了length regulator的速度。
