### ISSUE TITLE
About alignments

### ISSUE THREAD

**Issue by soobinseo** [xcmyz/FastSpeech#30]
Hi, Good reference to your good implementation. Such a nice work!
I have some questions about alignments (while getting the duration from pretrained-model)

It was understood that the proposed d_i (duration) can be applied only when the index increases monotonically. Since the alignment is not a perfect diagonal, the index value does not increase monotonically, when the argmax value is taken. How did you solve this case?

Thank you.

**Comment by xcmyz** [comment]
This's a good problem. Howerver, I didn't have a solution to fix it yet.

**Comment by doctor-xiang** [comment]
@xcmyz,may i ask how long can i train a better result.

**Comment by li-xx-5** [comment]
@xcmyz, may i ask how many epoches can i train a better result.

**Comment by xcmyz** [comment]
Depends on batchsize you set. Suggest >=100000 step.
