### ISSUE TITLE
UPDATE!

### ISSUE THREAD

**Issue by xcmyz** [xcmyz/FastSpeech#33]
1. Fix bugs in alignment;
2. Fix bugs in transformer;
3. Fix bugs in LengthRegulator;
4. Change the way to process audio;
5. Use waveglow to synthesize.

**Comment by rishikksh20** [comment]
@xcmyz Great implementation, Is anyway to train transfomer first so that later I used transformer itself to generate alignement and the then train FastSpeech on it this way we can achieve `sequence-level knowledge distillation` as mentioned in paper.
So basically I like to train transformer only first, is any way possible using this code itself for training.
Meanwhile I will write a training script with myself for train transformer just curious to ask  is it possible through in this code.

**Comment by rishikksh20** [comment]
Got following error after running `python preprocess.py`
```
Traceback (most recent call last):
  File "preprocess.py", line 59, in <module>
    main()
  File "preprocess.py", line 52, in main
    _, _, D = load_data(character, mel_gt_target, tacotron2)
  File "E:\Dev\FastSpeech\utils.py", line 160, in load_data
    D = get_D(alignment)
  File "E:\Dev\FastSpeech\utils.py", line 79, in get_D
    max_index = alignment[i].tolist().index(alignment[i].max())
ValueError: nan is not in list
```
Problem with alignment, so I printed it and got :
```
Align :  [[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
```
Are you aware of this kind of issue?

**Comment by xcmyz** [comment]
> Got following error after running `python preprocess.py`
> 
> ```
> Traceback (most recent call last):
>   File "preprocess.py", line 59, in <module>
>     main()
>   File "preprocess.py", line 52, in main
>     _, _, D = load_data(character, mel_gt_target, tacotron2)
>   File "E:\Dev\FastSpeech\utils.py", line 160, in load_data
>     D = get_D(alignment)
>   File "E:\Dev\FastSpeech\utils.py", line 79, in get_D
>     max_index = alignment[i].tolist().index(alignment[i].max())
> ValueError: nan is not in list
> ```
> 
> Problem with alignment, so I printed it and got :
> 
> ```
> Align :  [[nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]
>  ...
>  [nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]]
> ```
> 
> Are you aware of this kind of issue?

What pretrained model did you use? BTW, you can use `alignment.zip`.

**Comment by xcmyz** [comment]
> @xcmyz Great implementation, Is anyway to train transfomer first so that later I used transformer itself to generate alignement and the then train FastSpeech on it this way we can achieve `sequence-level knowledge distillation` as mentioned in paper.
> So basically I like to train transformer only first, is any way possible using this code itself for training.
> Meanwhile I will write a training script with myself for train transformer just curious to ask is it possible through in this code.

You need to modify `utils.py`.

**Comment by rishikksh20** [comment]
@xcmyz thanks will try... If it's possible can you please upload Fastspeech pretrain on `google drive` or `dropbox` etc because as I am not based in China I am not able to download it from Baidu.

**Comment by xcmyz** [comment]
> @xcmyz thanks will try... If it's possible can you please upload Fastspeech pretrain on `google drive` or `dropbox` etc because as I am not based in China I am not able to download it from Baidu.

Sorry.., You know, I am in China and my vpn isn't stable enough to put this model in Google drive...

**Comment by li-xx-5** [comment]
@xcmyz ,hello，when i train at the step of 272885,i cannot have a good result,the wav file has noise,what is wrong with that? How many steps should i train to have a good result,thank you .

**Comment by xcmyz** [comment]
> @xcmyz ,hello，when i train at the step of 272885,i cannot have a good result,the wav file has noise,what is wrong with that? How many steps should i train to have a good result,thank you .

\>= 100000

**Comment by runningJ** [comment]
I get the same error. The pretrained model download from nvidia. Please tell me how to solve this problem? @xcmyz

**Comment by xcmyz** [comment]
Use learning rate schedule.

**Comment by nikawool** [comment]
> 运行后出现以下错误 `python preprocess.py`
> 
> ```
> Traceback (most recent call last):
>   File "preprocess.py", line 59, in <module>
>     main()
>   File "preprocess.py", line 52, in main
>     _, _, D = load_data(character, mel_gt_target, tacotron2)
>   File "E:\Dev\FastSpeech\utils.py", line 160, in load_data
>     D = get_D(alignment)
>   File "E:\Dev\FastSpeech\utils.py", line 79, in get_D
>     max_index = alignment[i].tolist().index(alignment[i].max())
> ValueError: nan is not in list
> ```
> 
> 对齐问题，所以我将其打印并得到：
> 
> ```
> Align :  [[nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]
>  ...
>  [nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]
>  [nan nan nan ... nan nan nan]]
> ```
> 
> 您知道这种问题吗？

did you solve the problem? I have the same bug

**Comment by xcmyz** [comment]
No, maybe you can use alignment.zip directly or check the code about how to get alignment.

**Comment by xcmyz** [comment]
> > 运行后出现以下错误 `python preprocess.py`
> > ```
> > Traceback (most recent call last):
> >   File "preprocess.py", line 59, in <module>
> >     main()
> >   File "preprocess.py", line 52, in main
> >     _, _, D = load_data(character, mel_gt_target, tacotron2)
> >   File "E:\Dev\FastSpeech\utils.py", line 160, in load_data
> >     D = get_D(alignment)
> >   File "E:\Dev\FastSpeech\utils.py", line 79, in get_D
> >     max_index = alignment[i].tolist().index(alignment[i].max())
> > ValueError: nan is not in list
> > ```
> > 
> > 
> > 对齐问题，所以我将其打印并得到：
> > ```
> > Align :  [[nan nan nan ... nan nan nan]
> >  [nan nan nan ... nan nan nan]
> >  [nan nan nan ... nan nan nan]
> >  ...
> >  [nan nan nan ... nan nan nan]
> >  [nan nan nan ... nan nan nan]
> >  [nan nan nan ... nan nan nan]]
> > ```
> > 
> > 
> > 您知道这种问题吗？
> 
> did you solve the problem? I have the same bug

No, maybe you can use alignment.zip directly or check the code about how to get alignment.

**Comment by cutekih** [comment]
I get the same error. The pretrained model download from nvidia. Please tell me how to solve this problem? @xcmyz
I need to solve this problem in order to use my data.

**Comment by alokprasad** [comment]
getting same error, i cannot use alignment from alignment,zip as i need alignment with only 20 mels.
so that i can integrate with lpcnet
