### ISSUE TITLE
Model does not converge

### ISSUE THREAD

**Issue by coderLong** [xcmyz/FastSpeech#34]
I  use LJ data， alignments.zip , set batch_size = 16 to train model, 
but it does not converge after 20w step
Has anyone encountered this problem?

![loss](https://user-images.githubusercontent.com/12714902/67925051-2e0dfb80-fbed-11e9-89e4-d1e319869311.jpg)

**Comment by xcmyz** [comment]
Did you use  scheduled optimizer?
And you need bigger batch size, at least 32
