### ISSUE TITLE
112000 steps model I cannot unpack it

### ISSUE THREAD

**Issue by txz233** [xcmyz/FastSpeech#35]
It says the file has been broken. Is that possible for you to update it through?

Thanks!

**Comment by xcmyz** [comment]
This file needn't unpack.

**Comment by aguazul** [comment]
So where do you put it?  Download the file and then put it where?  Replace the file inpretrained_model folder for Tacotron2?

**Comment by xcmyz** [comment]
> So where do you put it? Download the file and then put it where? Replace the file inpretrained_model folder for Tacotron2?

put it in `model_new`, then run python `synthesis.py`
