### ISSUE TITLE
minor issue that might prevent some trouble later on

### ISSUE THREAD

**Issue by hash2430** [xcmyz/FastSpeech#36]
Hello,
Thanks a lot for publishing this amzaing repo.
I just have a little concern that I would like to let you know.
I see that under the 'paper' directory you have uploaded some papers.
I don't think that is a safe thing to do regarding copyrights.
The copyrights for each papers might differ, but just to be safe, how about replacing the papers with a link to it or just name of the papers???

**Comment by xcmyz** [comment]
Thank you very much
