### ISSUE TITLE
pre_trained checkpoint_12000xxx.tar can not be decompressed?

### ISSUE THREAD

**Issue by joan126** [xcmyz/FastSpeech#39]
Hi, I downloaded the pre_trained fastspeech model,  checkpoint_112000.pth.tar

when use tar -xf checkpoint_112000.pth.tar cmd on linux , error msg : 

```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

so, how to decompress it?

**Comment by xcmyz** [comment]
don't need to decompress
