### ISSUE TITLE
Is the dimension of the alignment of FastSpeech the same as that of tacotron2?

### ISSUE THREAD

**Issue by fastcode3d** [xcmyz/FastSpeech#4]
你好,请问tacotron2中的aliment具体是如何用的,导出之后直接作为alignment_target传到现有模型里吗?我看了一下原文,里吗好像有一步通过duration extractor将alignment转化为phoneme duration seuence的步骤,请问这部分对应您代码里的哪部分?

**Comment by xcmyz** [comment]
alignment.py

**Comment by xcmyz** [comment]
I'm sorry to reply you so late.

**Comment by fastcode3d** [comment]
您好,谢谢您的实现以及回复,对我很有帮助.
但关于alignment.py中的get_D函数我还有一些问题

def get_D(alignment):
    D = np.array([0 for _ in range(np.shape(alignment)[1])])

    for i in range(np.shape(alignment)[0]):
        max_index = alignment[i].tolist().index(alignment[i].max())
        D[max_index] = D[max_index] + 1

    for i in range(np.shape(D)[0]):
        if D[i] > 0:
            D[i] = D[i] - 1

    return D

其中为什么需要以下的步骤?


   for i in range(np.shape(D)[0]):
        if D[i] > 0:
            D[i] = D[i] - 1

我加上这一步之后,sum(D)=S-T(S and T are the lengths of the ground-truth spectrograms and phonemes),我对原文的理解应该是sum(D)=S.
希望您有空可以帮忙解答一下疑惑,谢谢!

**Comment by xcmyz** [comment]
不好意思，现在才看到。
那段代码具体的意思是
首先alignment的第二维是字符的长度，
for i in range(np.shape(alignment)[0]):
    max_index = alignment[i].tolist().index(alignment[i].max())
    D[max_index] = D[max_index] + 1
为的是找到每个mel列中对应的最大的字符的index
D就是一个长度为字符数的计数器

for i in range(np.shape(D)[0]):
    if D[i] > 0:
        D[i] = D[i] - 1
上面这一步的目的是为了将所有计数减一，并防止0变成负一，因为在之后的代码中，计数为1的字符实际上会扩充成2个，所以需要减一。

**Comment by fastcode3d** [comment]
好的,了解了,非常感谢!
