### ISSUE TITLE
 Breaks between words

### ISSUE THREAD

**Issue by limitforever** [xcmyz/FastSpeech#43]
In the original paper,the author proposes the breaks between words,and verifies that FastSpeech can add breaks between adjacent words by lengthening the duration of the space characters in the sentence, which can improve the prosody of voice. 
   So,how do you add breaks  between words in your code? 
   I'll be appreciated if you can help me.

**Comment by xcmyz** [comment]
modify the value of alpha.

**Comment by limitforever** [comment]
> modify the value of alpha.

I know alpha could cotrol the speed,but I mean adding a pause in the sentence，not adjusting the speed of the sentence.
For example,"I want to stay especially with you",a noticeable pause will be added after "especially",that is "I want to stay especially | with you".
can you give me some advice?

**Comment by xcmyz** [comment]
You can add more zero vector in the output of encoder.

**Comment by xiaoyangnihao** [comment]
> You can add more zero vector in the output of encoder.
@limitforever do you know how to do this now, can you share something ?
@xcmyz , Can you give more details about this?
