### ISSUE TITLE
The Mel

### ISSUE THREAD

**Issue by Liujingxiu23** [xcmyz/FastSpeech#47]
@xcmyz  
There is a great improvement since I tried this branch at Jun! Great Work

There is one thing I am completely confused.  You use log of mel as the feature, while the tacotron2 use DB of mel with normlization to [-4, 4]. What are the differences?  Does feature like tacotron work for fast-speech? Does the log of mel better for fast speech?

**Comment by xcmyz** [comment]
I just use the same method as Tacotron2 to process audio.
