### ISSUE TITLE
How long will the training process take ？

### ISSUE THREAD

**Issue by zceng** [xcmyz/FastSpeech#5]
I run `train_accelerated.py`, and start training.
Howerver, the estimated time is more than 9400000s ( about 100 days ).

Could you  introduce the training process and the training tine？
How many steps can we get a good result ？

I run the total training on 2 GPUs (Tesla V100).

**Comment by xcmyz** [comment]
You can train for about 1000 epoches.

**Comment by zceng** [comment]
OoOoOo, it still need 10 days. Do you reproduce the synthesis result ?

**Comment by xcmyz** [comment]
I am training this model.

**Comment by xcmyz** [comment]
I update readme.

**Comment by zceng** [comment]
Thanks for your answers. I also training this model and synthetic some audio, but the performance of the synthesis audio is worse than my expected. Maybe model parameter or structure need be adjusted.  

The paper mentions a method, named sequence-level knowledge distillation, which increase the MOS scores by 0.325. Do you think it is necessary to implement ?

**Comment by yinchyu** [comment]
训练的过程特别慢，而且betch_size 设置为8，如果设置过大就会out of mermory，这个要怎么解决，而且gpu的利用率并不高，话说你用这个训练过中文吗？，不知道这个训练中文结果好不好

**Comment by yinchyu** [comment]
我训练出来的结果也很差基本听不到人声，loss值大概在0.2然后感觉就不向下降了，这个是怎么回事？你了解其他的关于离线的tts如何实现的吗？

**Comment by zceng** [comment]
我的GPU显存有16G，batch_size 设置的64，训练过程会比较久，我用了大概3天。如果你的 batch_size 设置成 8，收敛速度理论上会更慢。

**Comment by NileZhou** [comment]
你的效果怎么样，作者给出的结果，感觉效果不是很好，有很多的背景音，除了这些还有哪些参数可以直接进行更改，比如步长，和其他的，我的gpu是8g的很难受！，帮帮我！

**Comment by NileZhou** [comment]
你没有停止训练了三天吗，感觉需要的时间太久了？

**Comment by YCY1998** [comment]
可以找你要一下微信吗？我的是YCYCYU1998

**Comment by YCY1998** [comment]
YINCYU1998

**Comment by li-xx-5** [comment]
模型能在CPU上面做到实时吗？

**Comment by xcmyz** [comment]
> 模型能在CPU上面做到实时吗？

需要剪枝
