### ISSUE TITLE
我想使用新的alignment，但是并未找到alignment.py文件

### ISSUE THREAD

**Issue by victor-wzq** [xcmyz/FastSpeech#51]

**Comment by victor-wzq** [comment]
用的是https://github.com/Rayhane-mamah/Tacotron-2 这个项目生成的alignment

**Comment by xcmyz** [comment]
修改这里[](https://github.com/xcmyz/FastSpeech/blob/5c3c2d1d12593ff2008da7363c9a87192f9391e5/utils.py#L143)

**Comment by xcmyz** [comment]
修改这里https://github.com/xcmyz/FastSpeech/blob/5c3c2d1d12593ff2008da7363c9a87192f9391e5/utils.py#L143

**Comment by victor-wzq** [comment]
> 修改这里
> 
> https://github.com/xcmyz/FastSpeech/blob/5c3c2d1d12593ff2008da7363c9a87192f9391e5/utils.py#L143

我生成了alignment，但是长度好像和模型输出的不一样。因为比较熟悉tensorflow所以使用了tensorflow编写的tacotron2

**Comment by xcmyz** [comment]
> > 修改这里
> > https://github.com/xcmyz/FastSpeech/blob/5c3c2d1d12593ff2008da7363c9a87192f9391e5/utils.py#L143
> 
> 我生成了alignment，但是长度好像和模型输出的不一样。因为比较熟悉tensorflow所以使用了tensorflow编写的tacotron2

用train时期的alignment

**Comment by ZhaoZeqing** [comment]
> > 修改这里
> > https://github.com/xcmyz/FastSpeech/blob/5c3c2d1d12593ff2008da7363c9a87192f9391e5/utils.py#L143
> 
> 我生成了alignment，但是长度好像和模型输出的不一样。因为比较熟悉tensorflow所以使用了tensorflow编写的tacotron2

Maybe **outputs_per_step=1** ?

**Comment by superhg2012** [comment]
Nvidia版本的T2只支持r=1, 要用tensorflow版本T2生成的alignment,需要设置 outputs_per_step=1 ，踩过这个坑
