### ISSUE TITLE
RuntimeError: shape '[1, 1, 47937]' is invalid for input of size 95874

### ISSUE THREAD

**Issue by aguazul** [xcmyz/FastSpeech#58]
I edited the preprocess.py file to point to a different dataset called jb.  The wav files and metadata.csv file are in the data/jb folder.

But when I run python preprocess_jb.py I get the error: RuntimeError: shape '[1, 1, 47937]' is invalid for input of size 95874

I'm not sure how to fix this!  Any clues? :)

Complete error message below.

Thank you!

(C:\Users\b\Anaconda3) C:\WINDOWS\system32>activate fastspeech

(fastspeech) C:\WINDOWS\system32>cd C:\Users\b\Documents\FastSpeech-master

(fastspeech) C:\Users\b\Documents\FastSpeech-master>python preprocess_jbpy
C:\Users\b\Anaconda3\envs\fastspeech\lib\site-packages\scipy\io\wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)
num_batches=1 and num_samples=47937.
Traceback (most recent call last):
  File "preprocess_jb.py", line 59, in <module>
    main()
  File "preprocess_jb.py", line 34, in main
    preprocess_ljspeech(path)
  File "preprocess_jb.py", line 19, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir)
  File "C:\Users\b\Documents\FastSpeech-master\data\ljspeech.py", line 15, in build_from_path
    out.append(_process_utterance(out_dir, index, wav_path, text))
  File "C:\Users\b\Documents\FastSpeech-master\data\ljspeech.py", line 26, in _process_utterance
    mel_spectrogram = Audio.tools.get_mel(wav_path).numpy().astype(np.float32)
  File "C:\Users\b\Documents\FastSpeech-master\Audio\tools.py", line 29, in get_mel
    melspec = _stft.mel_spectrogram(audio_norm)
  File "C:\Users\b\Documents\FastSpeech-master\Audio\stft.py", line 155, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "C:\Users\b\Documents\FastSpeech-master\Audio\stft.py", line 59, in transform
    input_data = input_data.view(num_batches, 1, num_samples)
RuntimeError: shape '[1, 1, 47937]' is invalid for input of size 95874

(fastspeech) C:\Users\b\Documents\FastSpeech-master>

**Comment by xcmyz** [comment]
> I edited the preprocess.py file to point to a different dataset called jb. The wav files and metadata.csv file are in the data/jb folder.
> 
> But when I run python preprocess_jb.py I get the error: RuntimeError: shape '[1, 1, 47937]' is invalid for input of size 95874
> 
> I'm not sure how to fix this! Any clues? :)
> 
> Complete error message below.
> 
> Thank you!
> 
> (C:\Users\b\Anaconda3) C:\WINDOWS\system32>activate fastspeech
> 
> (fastspeech) C:\WINDOWS\system32>cd C:\Users\b\Documents\FastSpeech-master
> 
> (fastspeech) C:\Users\b\Documents\FastSpeech-master>python preprocess_jbpy
> C:\Users\b\Anaconda3\envs\fastspeech\lib\site-packages\scipy\io\wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
> WavFileWarning)
> num_batches=1 and num_samples=47937.
> Traceback (most recent call last):
> File "preprocess_jb.py", line 59, in
> main()
> File "preprocess_jb.py", line 34, in main
> preprocess_ljspeech(path)
> File "preprocess_jb.py", line 19, in preprocess_ljspeech
> metadata = ljspeech.build_from_path(in_dir, out_dir)
> File "C:\Users\b\Documents\FastSpeech-master\data\ljspeech.py", line 15, in build_from_path
> out.append(_process_utterance(out_dir, index, wav_path, text))
> File "C:\Users\b\Documents\FastSpeech-master\data\ljspeech.py", line 26, in _process_utterance
> mel_spectrogram = Audio.tools.get_mel(wav_path).numpy().astype(np.float32)
> File "C:\Users\b\Documents\FastSpeech-master\Audio\tools.py", line 29, in get_mel
> melspec = _stft.mel_spectrogram(audio_norm)
> File "C:\Users\b\Documents\FastSpeech-master\Audio\stft.py", line 155, in mel_spectrogram
> magnitudes, phases = self.stft_fn.transform(y)
> File "C:\Users\b\Documents\FastSpeech-master\Audio\stft.py", line 59, in transform
> input_data = input_data.view(num_batches, 1, num_samples)
> RuntimeError: shape '[1, 1, 47937]' is invalid for input of size 95874
> 
> (fastspeech) C:\Users\b\Documents\FastSpeech-master>

You need make sure audio in your dataset has the same sample rate and bit as audio in LJSpeech.

**Comment by aguazul** [comment]
Ok, cool.  Thank you!  Do you have a recommended tool to change the sample rate and bit depth of my data?

**Comment by xcmyz** [comment]
> Ok, cool. Thank you! Do you have a recommended tool to change the sample rate and bit depth of my data?

You can try http://sox.sourceforge.net/

**Comment by aguazul** [comment]
Thank you!  That was helpful.  I did try SoX as you recommended, but eventually I used https://dbpoweramp.com/dmc.htm

The problem ended up being that my wav files were in stereo but the LJSpeech dataset is mono channel. I was able to use the software to convert all the wav files from stereo to mono all at once using batch processing. I selected all wav files in the folder, right clicked, and selected "Convert to" option which is available after installing dbpoweramp software.

Thanks so much!

**Comment by Ahmad-noborders** [comment]
hi @aguazul  thank you so much for your work. i am training it on korean data. i have setup all my data in the data folder and here is detail of my data

> Sample rate: 44100

> Channels: 1

> Subtype:`` PCM_16

- [x] i have changed the sample rate in audio/hparams.py file with 44100. but i am still getting error 

- [x] i have also changed the text/symbols.py file with korean letters. 

`Traceback (most recent call last):
  File "preprocess.py", line 61, in <module>
    main()
  File "preprocess.py", line 34, in main
    preprocess_ljspeech(path)
  File "preprocess.py", line 19, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir)
  File "/content/drive/My Drive/voice/FastSpeech/data/ljspeech.py", line 15, in build_from_path
    out.append(_process_utterance(out_dir, index, wav_path, text))
  File "/content/drive/My Drive/voice/FastSpeech/data/ljspeech.py", line 26, in _process_utterance
    mel_spectrogram = Audio.tools.get_mel(wav_path).numpy().astype(np.float32)
  File "/content/drive/My Drive/voice/FastSpeech/audio/tools.py", line 29, in get_mel
    melspec = _stft.mel_spectrogram(audio_norm)
  File "/content/drive/My Drive/voice/FastSpeech/audio/stft.py", line 154, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "/content/drive/My Drive/voice/FastSpeech/audio/stft.py", line 58, in transform
    input_data = input_data.view(num_batches, 1, num_samples)
RuntimeError: shape '[1, 1, 155520]' is invalid for input of size 311040`

can you please help me solving this issue. Thanks
