### ISSUE TITLE
preprocess.py 好像运行不了

### ISSUE THREAD

**Issue by cythc** [xcmyz/FastSpeech#62]
max_index = alignment[i].tolist().index(alignment[i].max())
ValueError: nan is not in list

得到的alignments，mel_outputs 都是Nan

**Comment by xcmyz** [comment]
> max_index = alignment[i].tolist().index(alignment[i].max())
> ValueError: nan is not in list
> 
> 得到的alignments，mel_outputs 都是Nan

你可以直接使用alignment.zip，nan的问题可能是版本或者是tacotron2 pretrained model不适配的问题
