### ISSUE TITLE
FastSpeech quality?

### ISSUE THREAD

**Issue by qo4on** [xcmyz/FastSpeech#66]
Why is the quality of this pretrained model significantly worse than [these FastSpeech examples](https://speechresearch.github.io/fastspeech/)?

**Comment by xcmyz** [comment]
> Why is the quality of this pretrained model significantly worse than [these FastSpeech examples](https://speechresearch.github.io/fastspeech/)?

1. I use character as input not phone;
2. maybe there are some bugs in the Implementation of transformer module;
3. I use smaller batch size.
