### ISSUE TITLE
Early stopping? Loss

### ISSUE THREAD

**Issue by BuaaAlban** [xcmyz/FastSpeech#68]
Is there an early stopping or something to judge the result?
When do the loss values converge(or little than which value means a good model)? 
Mel Loss: 0.3682, Mel PostNet Loss: 0.3648, Duration Loss: 0.4818;

**Comment by xcmyz** [comment]
> Is there an early stopping or something to judge the result?
> When do the loss values converge(or little than which value means a good model)?
> Mel Loss: 0.3682, Mel PostNet Loss: 0.3648, Duration Loss: 0.4818;

the model will synthsize acceptable speech when step is 10k using batchsize = 32

**Comment by BuaaAlban** [comment]
> > Is there an early stopping or something to judge the result?
> > When do the loss values converge(or little than which value means a good model)?
> > Mel Loss: 0.3682, Mel PostNet Loss: 0.3648, Duration Loss: 0.4818;
> 
> the model will synthsize acceptable speech when step is 10k using batchsize = 32

Yes, the synthsized speech can be recognized, with a little noise with G-Lim vocoder, and maybe it doesn't need that much steps using pretrained model.
BTW, the vocoder waveglow and tacotron can't be used now
