### ISSUE TITLE
any result samples?

### ISSUE THREAD

**Issue by lucasjinreal** [xcmyz/FastSpeech#7]
Any result samples?

**Comment by xcmyz** [comment]
I will put result wav here soon.

**Comment by lucasjinreal** [comment]
hoping for that. BTW, how long it takes when synthnsis a sentences?

**Comment by xcmyz** [comment]
I have put and update readme.

**Comment by lucasjinreal** [comment]
@xcmyz  The voice sounds a little robotness. What do u think of it compares to tacotron2? Seems not as good as tacotron2

**Comment by xcmyz** [comment]
This model need to be trained for more epochs.

**Comment by lucasjinreal** [comment]
@xcmyz Hope you update some decent samples when the model converges. (Even though I don't know if it can converge eventually or not)

**Comment by epochsimate** [comment]
any update on this? has anyone managed to train this model to the point where it outperforms tacotron2?
