### ISSUE TITLE
pretrain model link invalid

### ISSUE THREAD

**Issue by 5859wang** [xcmyz/FastSpeech#73]
Can you provide a link to the pretrain again?

**Comment by 5859wang** [comment]
Can you provide a trained model waveglow_256channels.pt and tacotron2_statedict.pt link?

**Comment by xcmyz** [comment]
> Can you provide a trained model waveglow_256channels.pt and tacotron2_statedict.pt link?

https://github.com/NVIDIA/tacotron2

**Comment by 5859wang** [comment]
This link cannot be downloaded

**Comment by 5859wang** [comment]
can you  add  me qq  984294205,I really want to implement this model。 or provide the file waveglow_256channels.pt and tacotron2_statedict.pt give me,appreciate you

**Comment by chazo1994** [comment]
@xcmyz Could you provide pretrain model of LJ-Speech, I would like to test quality and performance on CPU.

**Comment by xcmyz** [comment]
> @xcmyz Could you provide pretrain model of LJ-Speech, I would like to test quality and performance on CPU.

I update README

**Comment by chazo1994** [comment]
@xcmyz  Thank you so much.
