### ISSUE TITLE
FastSpeech2 support?

### ISSUE THREAD

**Issue by LLianJJun** [xcmyz/FastSpeech#76]
Hello, I find an interested paper(https://arxiv.org/pdf/2006.04558.pdf) called FastSpeech2. 
It is an advanced version of FastSpeech, which eliminates the teacher model and directly combines PWG training to generate speech directly from text. The results of the paper show that the phonetic quality and synthesis speed of speech are good.
Are you planning to implement Fastspeech2?

**Comment by dathudeptrai** [comment]
@LLianJJun i just released the fastspeech2 model, and the quality seem quite good compared with fastspeech1, fastspeech2s is training now :))). pls, checkout https://github.com/dathudeptrai/TensorflowTTS

**Comment by LLianJJun** [comment]
@dathudeptrai 
thanks! :))
