### ISSUE TITLE
wav in chinese

### ISSUE THREAD

**Issue by li-xx-5** [xcmyz/FastSpeech#95]
[165000_1.zip](https://github.com/xcmyz/FastSpeech/files/5744468/165000_1.zip)
为什么输入标贝数据集，合成的汉语是这样的？是因为对其没弄好吗

**Comment by xcmyz** [comment]
> [165000_1.zip](https://github.com/xcmyz/FastSpeech/files/5744468/165000_1.zip)
> 为什么输入标贝数据集，合成的汉语是这样的？是因为对其没弄好吗

我觉得是的
